// This file is auto-generated by @hey-api/openapi-ts

import type { ReadTasksResponse, CreateTaskResponse, ReadTaskResponse, UpdateTaskResponse } from './types.gen';

const taskOutSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const paginatedTaskOutSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return taskOutSchemaResponseTransformer(item);
    });
    return data;
};

export const readTasksResponseTransformer = async (data: any): Promise<ReadTasksResponse> => {
    data = paginatedTaskOutSchemaResponseTransformer(data);
    return data;
};

export const createTaskResponseTransformer = async (data: any): Promise<CreateTaskResponse> => {
    data = taskOutSchemaResponseTransformer(data);
    return data;
};

export const readTaskResponseTransformer = async (data: any): Promise<ReadTaskResponse> => {
    data = taskOutSchemaResponseTransformer(data);
    return data;
};

export const updateTaskResponseTransformer = async (data: any): Promise<UpdateTaskResponse> => {
    data = taskOutSchemaResponseTransformer(data);
    return data;
};